
export const actionType = {
    
    // HOME

    HOME: 'HOME',

    INCREMENT_WILD_STEP_COUNTER: 'INCREMENT_WILD_STEP_COUNTER',
    DECREMENT_WILD_STEP_COUNTER: 'DECREMENT_WILD_STEP_COUNTER',
    RESET_WILD_STEP_COUNTER: 'RESET_WILD_STEP_COUNTER',
    RESET_DITTO: 'RESET_DITTO',
    ACTIVATE_WILD: 'ACTIVATE_WILD',
    DEACTIVATE_WILD: 'DEACTIVATE_WILD',

    // HOUSE
    
    HOUSE: 'HOUSE',
    HOUSE_RESET_DITTO: 'HOUSE_RESET_DITTO',
    HOUSE_D_PAD: 'HOUSE_D_PAD',

    // BATTLE

    ENEMY_SPRITE: 'ENEMY_SPRITE',
    BATTLE: 'BATTLE',
    BATTLE_ACTIONS: 'BATTLE_ACTIONS',
    ATTACK_OPTIONS: 'ATTACK_OPTIONS',
    BAG_OPTIONS: 'BAG_OPTIONS',
    POKEMON_OPTIONS: 'POKEMON_OPTIONS',
    CHOOSE: 'CHOOSE',
    ATTACK: 'ATTACK',
    RESET_ENEMY_HEALTH: 'RESET_ENEMY_HEALTH',
    ENEMY_BULBASAUR: 'ENEMY_BULBASAUR',
    ENEMY_DITTO: 'ENEMY_DITTO',
    ENEMY_RNG: 'ENEMY_RNG'
}