export const actionMovement = {

    // HOME ???
    
    MOVE_UP_LEFT: 'MOVE_UP_LEFT',
    MOVE_SPRITE_UP_LEFT: 'MOVE_SPRITE_UP_LEFT',
    MOVE_UP: 'MOVE_UP',
    MOVE_SPRITE_UP: 'MOVE_SPRITE_UP',
    MOVE_UP_RIGHT: 'MOVE_UP_RIGHT',
    MOVE_SPRITE_UP_RIGHT: 'MOVE_SPRITE_UP_RIGHT',
    MOVE_LEFT: 'MOVE_LEFT',
    MOVE_SPRITE_LEFT: 'MOVE_SPRITE_LEFT',
    MOVE_RIGHT: 'MOVE_RIGHT',
    MOVE_SPRITE_RIGHT: 'MOVE_SPRITE_RIGHT',
    MOVE_DOWN_LEFT: 'MOVE_DOWN_LEFT',
    MOVE_SPRITE_DOWN_LEFT: 'MOVE_SPRITE_DOWN_LEFT',
    MOVE_DOWN: 'MOVE_DOWN',
    MOVE_SPRITE_DOWN: 'MOVE_SPRITE_DOWN',
    MOVE_DOWN_RIGHT: 'MOVE_DOWN_RIGHT',
    MOVE_SPRITE_DOWN_RIGHT: 'MOVE_SPRITE_DOWN_RIGHT',
}