
export const actionType = {
    
    // HOME

    HOME: 'HOME',
    MOVE_UP_LEFT: 'MOVE_UP_LEFT',
    MOVE_SPRITE_UP_LEFT: 'MOVE_SPRITE_UP_LEFT',
    MOVE_UP: 'MOVE_UP',
    MOVE_SPRITE_UP: 'MOVE_SPRITE_UP',
    MOVE_UP_RIGHT: 'MOVE_UP_RIGHT',
    MOVE_SPRITE_UP_RIGHT: 'MOVE_SPRITE_UP_RIGHT',
    MOVE_LEFT: 'MOVE_LEFT',
    MOVE_SPRITE_LEFT: 'MOVE_SPRITE_LEFT',
    MOVE_RIGHT: 'MOVE_RIGHT',
    MOVE_SPRITE_RIGHT: 'MOVE_SPRITE_RIGHT',
    MOVE_DOWN_LEFT: 'MOVE_DOWN_LEFT',
    MOVE_SPRITE_DOWN_LEFT: 'MOVE_SPRITE_DOWN_LEFT',
    MOVE_DOWN: 'MOVE_DOWN',
    MOVE_SPRITE_DOWN: 'MOVE_SPRITE_DOWN',
    MOVE_DOWN_RIGHT: 'MOVE_DOWN_RIGHT',
    MOVE_SPRITE_DOWN_RIGHT: 'MOVE_SPRITE_DOWN_RIGHT',
    INCREMENT_WILD_STEP_COUNTER: 'INCREMENT_WILD_STEP_COUNTER',
    DECREMENT_WILD_STEP_COUNTER: 'DECREMENT_WILD_STEP_COUNTER',
    RESET_WILD_STEP_COUNTER: 'RESET_WILD_STEP_COUNTER',
    RESET_DITTO: 'RESET_DITTO',
    ACTIVATE_WILD: 'ACTIVATE_WILD',
    DEACTIVATE_WILD: 'DEACTIVATE_WILD',

    // HOUSE
    
    HOUSE: 'HOUSE',
    HOUSE_RESET_DITTO: 'HOUSE_RESET_DITTO',
    HOUSE_D_PAD: 'HOUSE_D_PAD',

    // BATTLE

    BATTLE: 'BATTLE',
    BATTLE_ACTIONS: 'BATTLE_ACTIONS',
    ATTACK_OPTIONS: 'ATTACK_OPTIONS',
    BAG_OPTIONS: 'BAG_OPTIONS',
    POKEMON_OPTIONS: 'POKEMON_OPTIONS'
}